### ISSUE TITLE
Review StatementExtractParameters

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Main#1056]
```
return g(true, 1 + x(1 + 2), new Object());
```
==>
```
int i = 1 + x(1 + 2);
return g(true, i, new Object());
```
==>
```
int j = 1 + 2;
int i = 1 + x(j);
Object o = new Object();
return g(true, i, o);
```

**Comment by yuvalsimon** [comment]
@OriRoth checkout #1286, I wrote tests for the bugs I already mentioned (except the duplicate imports), currently ignored

**Comment by yuvalsimon** [comment]
In class _type -> baptize(string,string)_ (also in many other functions): 
```
static inner.implementation baptize(final String name, final String description) {
...
return bring(name);
...
```
goes to
``
static inner.implementation baptize(final String name, final String description) {
...
implementation i1 = bring(name);
return i1;
...
``
the type of i1 should be inner.implementation (inner is enum defined in class type)

**Comment by yuvalsimon** [comment]
Also have problems with generic types:
```
public WithStreamParameter(Stream<?> s, String str) {
      this.list = s.collect(Collectors.toList());
	checkNotNull(str);
    }
```
goes to
```
public WithStreamParameter(Stream<?> s, String str) {
      Collector<?, ?, ?> c1 = Collectors.toList();
	this.list = s.collect(c1);
	checkNotNull(str);
    }
```
_collect_ is not applicable for this type (the correct type is `Collector<Object, ?, List<Object>>`)

**Comment by OriRoth** [comment]
I need a complete code, otherwise nothing will happen and I won't be able to recreate the problem... please specify project+file+line number.

**Comment by OriRoth** [comment]
@yuvalsimon ???

**Comment by OriRoth** [comment]
First problem is solved, though it may produce a warning...
The second problem is solved- this is a tricky one, because even Eclipse's "Extract local" fail on this case.

**Comment by yuvalsimon** [comment]
Another bug - not importing generic parameters - SpartanizerPlugin project class HeadlessSpartanizer, first command of method _apply_
The first problem I mentioned is not solved yet, try on SpartanizerProject project, class EnvironmentVisitor, method createInformation.

**Comment by OriRoth** [comment]
OK solved it... the problem was not generic parameters but non-visible imports (i.e. it made an import, but it was errored).
What is this "first problem"? Qualified type names? I fully zoomed `EnvironmentVisitor` with no exception... (though it may have been fixed somehow on the way).

**Comment by yuvalsimon** [comment]
It's too much, now there are unresolved classes, try to athenize project _spartan->GraphTest.java_
Another thing in this class - we have this fluent code:
```
final Graph<String> src = new Graph.Builder<String>() //
        .newEdge("A", "C").newEdge("B", "C").newEdge("C", "D")//
        .newEdge("C", "E").newEdge("F", "G").newEdge("H", "I")//
        .newEdge("I", "H").newVertex("J")//
        .build();
```
Should athenize such fluent codes?
It gives this code:
```
final Graph<String> src;
    Builder<String> s1;
    Builder<String> s3;
    Builder<String> s5;
    Builder<String> s6;
    Builder<String> s7;
    Builder<String> s8;
    Builder<String> s9;
    Builder<String> s10;
    Builder<String> s11;
    s11 = new Graph.Builder<String>();
    s10 = s11.newEdge("A", "C");
    s9 = s10.newEdge("B", "C");
    s8 = s9.newEdge("C", "D");
    s7 = s8.newEdge("C", "E");
    s6 = s7.newEdge("F", "G");
    s5 = s6.newEdge("H", "I");
    s3 = s5.newEdge("I", "H");
    s1 = s3.newVertex("J");
```
Should consider to only extract arguments of methods, not to take apart such fluent expressions

**Comment by OriRoth** [comment]
Fixed. It was my bad- we need import for *nested* class even if it is in the same package.
About the fluent API- looks fine to me. We can insert some heuristics if we want, anytime.

**Comment by yuvalsimon** [comment]
Need to check also that you don't import private class, check _fluent.ly->FilesGenerator_

**Comment by OriRoth** [comment]
Fixed. Also, I started fixing *warnings* as well as errors, so you may inform me of them as well.

**Comment by OriRoth** [comment]
@yuvalsimon are there more bugs here? If not, please close this. I am already aware of #1155.
